INSERT INTO WhoBeDo (userName, email, password, createdAt, updatedAt, active, isAdmin) VALUES ('Sean','persona1@gmail.com','admin123x', '2018-06-12', '2018-06-12', true, true);
INSERT INTO WhoBeDo (userName, email, password, createdAt, updatedAt, active, isAdmin) VALUES ('Tony','persona1@gmail.com','admin123x', '2018-06-12', '2018-06-12', true, true);
INSERT INTO WhoBeDo (userName, email, password, createdAt, updatedAt, active, isAdmin) VALUES ('Janel','persona1@gmail.com','admin123x', '2018-06-12', '2018-06-12', true, true);
INSERT INTO WhoBeDo (userName, email, password, createdAt, updatedAt, active, isAdmin) VALUES ('Alex','persona1@gmail.com','admin123x', '2018-06-12', '2018-06-12', true, true);
INSERT INTO WhoBeDo (userName, email, password, createdAt, updatedAt, active, isAdmin) VALUES ('baca1','persona1@gmail.com','Xadmin123x', '2018-06-12', '2018-06-12', true, true);
INSERT INTO WhoBeDo (userName, email, password, createdAt, updatedAt, active, isAdmin) VALUES ('baca2','persona1@gmail.com','Xadmin123x', '2018-06-12', '2018-06-12', false, false);


INSERT INTO artists	(groupName, contactName, contactEmail, contactPhone, personalWebsite, instagramLink, facebookLink, spotifyLink, twitterLink, soundcloudLink, youtubeLink, appleMusicLink, otherLink1, otherLink2, comments, upcomingProjects, createdAt, updatedAt) VALUES ('Wrekin Jam','Paulie Gualtieri','pgcrew999@gmail.com','(862) 555-5150','https://www.whodat.com','https://www.instagram.com','https://www.facebook.com','https://www.spotify.com','https://twitter.com/','https://soundcloud.com/','https://www.youtube.com/','https://www.apple.com/apple-music/','null','null','add comments here','null','2018-06-12','2018-06-12');
INSERT INTO artists	(groupName, contactName, contactEmail, contactPhone, personalWebsite, instagramLink, facebookLink, spotifyLink, twitterLink, soundcloudLink, youtubeLink, appleMusicLink, otherLink1, otherLink2, comments, upcomingProjects, createdAt, updatedAt) VALUES ('Beat Down','Vito Spatafore','vitoprimo@gmail.com','(862) 555-5150','https://www.whodat.com','https://www.instagram.com','https://www.facebook.com','https://www.spotify.com','https://twitter.com/','https://soundcloud.com/','https://www.youtube.com/','https://www.apple.com/apple-music/','null','null','add comments here','null','2018-06-12','2018-06-12');
INSERT INTO artists	(groupName, contactName, contactEmail, contactPhone, personalWebsite, instagramLink, facebookLink, spotifyLink, twitterLink, soundcloudLink, youtubeLink, appleMusicLink, otherLink1, otherLink2, comments, upcomingProjects, createdAt, updatedAt) VALUES ('Walk it Off','Richie Aprile','richie4hire@gmail.com','(862) 555-5150','https://www.whodat.com','https://www.instagram.com','https://www.facebook.com','https://www.spotify.com','https://twitter.com/','https://soundcloud.com/','https://www.youtube.com/','https://www.apple.com/apple-music/','null','null','add comments here','null','2018-06-12','2018-06-12');
INSERT INTO artists	(groupName, contactName, contactEmail, contactPhone, personalWebsite, instagramLink, facebookLink, spotifyLink, twitterLink, soundcloudLink, youtubeLink, appleMusicLink, otherLink1, otherLink2, comments, upcomingProjects, createdAt, updatedAt) VALUES ('Gold Snitchin','Phil Leotardo','webewatchinyou@gmail.com','(862) 555-5150','https://www.whodat.com','https://www.instagram.com','https://www.facebook.com','https://www.spotify.com','https://twitter.com/','https://soundcloud.com/','https://www.youtube.com/','https://www.apple.com/apple-music/','null','null','add comments here','null','2018-06-12','2018-06-12');
INSERT INTO artists	(groupName, contactName, contactEmail, contactPhone, personalWebsite, instagramLink, facebookLink, spotifyLink, twitterLink, soundcloudLink, youtubeLink, appleMusicLink, otherLink1, otherLink2, comments, upcomingProjects, createdAt, updatedAt) VALUES ('Bada Bing','Artie Bucco','buccobeppo@gmail.com','(862) 555-5150','https://www.whodat.com','https://www.instagram.com','https://www.facebook.com','https://www.spotify.com','https://twitter.com/','https://soundcloud.com/','https://www.youtube.com/','https://www.apple.com/apple-music/','null','null','add comments here','null','2018-06-12','2018-06-12');
INSERT INTO artists	(groupName, contactName, contactEmail, contactPhone, personalWebsite, instagramLink, facebookLink, spotifyLink, twitterLink, soundcloudLink, youtubeLink, appleMusicLink, otherLink1, otherLink2, comments, upcomingProjects, createdAt, updatedAt) VALUES ('Silver Cadillac','Silvio Dante','smoveride@gmail.com','(862) 555-5150','https://www.whodat.com','https://www.instagram.com','https://www.facebook.com','https://www.spotify.com','https://twitter.com/','https://soundcloud.com/','https://www.youtube.com/','https://www.apple.com/apple-music/','null','null','add comments here','null','2018-06-12','2018-06-12');


INSERT INTO events	(eventName, venueName, eventDate, startTime, showLength, eventAddress, eventCity, eventState, eventZip, eventCountry, coordinates, ageRestrictions, showDetails, eventLink, artist_01, artist_02, artist_03, createdAt, updatedAt) VALUES ('Sleep wit da Fishes 2018','The Forum','2018-08-01','21:00:00','03:00:00','3900 W Manchester Blvd','Inglewood','CA','90305','USA','33.958056,-118.341944','none', 'Directions: add; Parking: add;', 'add event link', 'Wrekin Jam','Bada Bing', 'artist_03','2018-06-12','2018-06-12');
INSERT INTO events	(eventName, venueName, eventDate, startTime, showLength, eventAddress, eventCity, eventState, eventZip, eventCountry, coordinates, ageRestrictions, showDetails, eventLink, artist_01, artist_02, artist_03, createdAt, updatedAt) VALUES ('Sleep wit da Fishes 2018','The Forum','2018-08-02','21:00:00','03:00:00','3900 W Manchester Blvd','Inglewood','CA','90305','USA','33.958056,-118.341944','none', 'Directions: add; Parking: add;', 'add event link', 'Beat Down','Walk it Off', 'Gold Snitchin','2018-06-12','2018-06-12');
INSERT INTO events	(eventName, venueName, eventDate, startTime, showLength, eventAddress, eventCity, eventState, eventZip, eventCountry, coordinates, ageRestrictions, showDetails, eventLink, artist_01, artist_02, artist_03, createdAt, updatedAt) VALUES ('Paulie did It','Freak City','2018-08-24','23:00:00','02:00:00','6613 W Sunset Blvd','Hollywood','CA','90028','USA','34.0982367,-118.335727,17','21', 'Directions: add; Parking: add;', 'add event link', 'Beat Down','artist_02', 'artist_03','2018-06-12','2018-06-12');


INSERT INTO SignUps (signUpName, signUpMobile, signUpEmail, createdAt, updatedAt, active) VALUES ('Guido Darock','310-555-5150','guidodude@gmail.com','2018-06-12','2018-06-12',true);
INSERT INTO SignUps (signUpName, signUpMobile, signUpEmail, createdAt, updatedAt, active) VALUES ('Lisa McLisa','310-555-5150','lisaisaclone@gmail.com','2018-06-12','2018-06-12',true);
INSERT INTO SignUps (signUpName, signUpMobile, signUpEmail, createdAt, updatedAt, active) VALUES ('Brittany Kim','310-555-5150','bkimfly@gmail.com','2018-06-12','2018-06-12',true);

